# Generated by Django 4.2.5 on 2023-09-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0003_alter_customuser_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='settings',
        ),
    ]
