# Generated by Django 4.2.5 on 2023-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0004_remove_customuser_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='settings',
            field=models.JSONField(default={'font': 0, 'theme': 0}, verbose_name='settings'),
        ),
    ]
