# Generated by Django 4.2.5 on 2023-09-27 21:33

from django.db import migrations, models
import userface.models


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0005_customuser_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='settings',
            field=models.JSONField(default=userface.models.get_default_settings, verbose_name='settings'),
        ),
    ]
